### ISSUE TITLE
SEO and SSR alternative idea

### ISSUE THREAD

**Issue by tristantbg** [f-mahler/vuekit#1]
Hi @f-mahler,

I stumbled your repo which is quite promising !
The only thing that get me out of using Vue is SEO.
A solution would be to have Kirby on a PHP server and use it as an API, and a Nuxt app on a Node server with SSR, but this adds a lot of configuration options and usually clients have only a PHP server.
I was wondering if we could use some basic SEO content in each Kirby page and if JS in enabled we switch into Vue SPA mode.
What do you think of this technique ?
https://github.com/tristantbg/vuekit/blob/master/site/templates/default.php
As I don't know Vue that well, you could maybe see problems that this would create ?
I guess one of the big problems of this is to stick with Kirby content url routing hierarchy in both the Kirby app and Vue app, but we could use https://github.com/omz13/kirby3-xmlsitemap out of the box and the whole website would be crawled well by search engines.

Thank you for your input,
T

**Comment by f-mahler** [comment]
Hi Tristan,

Thanks for your message, I think it is an interesting problem.

The Vuekit repo is something I use for smaller portfolio websites where SEO
is not of such importance. I only handle the main entry with a specific
description directly from Kirby, as you probably noticed, but it could be a
lot better I admit.

In general when I have a bigger project I normally use Nuxt (which deals
really well with SEO) connected to Kirby via an API, but as you say it is
not always possible depending on the client, and maybe also a bit of an
overkill sometimes.

I would gladly look into it and see if it is not possible to handle it on
the vue-side of things with something like: https://github.com/nuxt/vue-meta
I'm afraid it gets messy if you start outputting a xml sitemap from Kirby
and your frontend is not following the exact routing of kirby, though it
could be a solution.

Let me look into it and get back to you.

All the best,
Frederik

p.s. On peut parler en français si jamais, je crois qu'on a un ami en
commun, Romain Cazier :)

**Comment by tristantbg** [comment]
Hi Frederik,

Thanks a lot for your prompt and precise response.
_(Super que tu connaisses Romain, je crois aussi qu'on a Luke aussi en commun ;) Oui on pourrait parler en francais mais ca permet aux autres utilisateurs de Github de suivre la conversation!)_
I understand it is better to stick only with Vue tools to keep a good consistency everywhere.
Nuxt make it a bit difficult to generate dynamic urls no ? With this php snippet approach you don't need to setup this or have to regenerate the whole website in static. 🤔
Each time a client update the Kirby, a webhook triggers the deployment of the Nuxt app, but I am trying to make a Vue/PHP only solution without the need to use Node (maybe it is a bit utopic).

Thanks again for your concern !
Tristan

**Comment by f-mahler** [comment]
Hi Tristan. (Je n'ai pas capté que c'était un issue public sur github, on continue bien sûr en anglais 🤦‍♂) 

I've think it is possible to do what you want with vue-meta. It can inject the meta data specific to each page (eg. title, description, etc.), while still being reactive. 

I've updated the repo with a solution, and I will test it on one of my sites, to see how it works on search engines. Hopefully it works, but not sure if search engines are able to crawl meta information which is injected reactively, as I haven't tested it.

**Comment by tristantbg** [comment]
Hi Frederik,

Thank you very much for these additions ! Let me know if it works on your test site.
Let's hope crawlers will analyse JS in a near future haha

Best,
T

**Comment by tristantbg** [comment]
Hi Frederik,

How did the vue-meta SEO test went ?

Best,
T

**Comment by f-mahler** [comment]
It didn't manage to crawl descriptions but titles works fine. 
I think a Prerendering-SPA or a SSR are the only alternative solutions at the moment.

**Comment by tristantbg** [comment]
> It didn't manage to crawl descriptions but titles works fine.
> I think a Prerendering-SPA or a SSR are the only alternative solutions at the moment.

Thank you for your feedback. I guess it is the only way to go.
I found out Now.sh can give you a free SSR alternative, worth to try : https://fr.nuxtjs.org/faq/now-deployment/

**Comment by tristantbg** [comment]
Sorry, above was not the right link, here you go :
https://github.com/nuxt/now-builder

**Comment by tristantbg** [comment]
Hey @f-mahler 

Someone found an alternative way to generate meta for SEO : 
https://github.com/johannschopplich/kirby-vue3-starterkit

Best,
T

**Comment by f-mahler** [comment]
Hey @tristantbg.

This looks amazing. Just tried it out. Fixes so many problems. Thanks for the tip!
