### ISSUE TITLE
Projects Overview doesn't work

### ISSUE THREAD

**Issue by KPLehmann** [f-mahler/vuekit#2]
After installation, Projects didn't show instantly. 
After changing "files" to "images" on line 4 in Projects.vue, it worked.

**Comment by KPLehmann** [comment]
After installation, Projects didn't show instantly. 
After changing "file" to "images" on line 4 in Projects.vue, it worked.

**Comment by f-mahler** [comment]
Thanks. Fixed in the latest commit
